-- ===== 1. DEPARTMENTS (부서) =====
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    budget_limit BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ===== 2. USERS (임직원) =====
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    employee_number VARCHAR(50) NOT NULL,
    title VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

-- ===== 3. BUDGET_REQUESTS (예산신청서) =====
CREATE TABLE budget_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    budget_amount BIGINT NOT NULL,
    comment TEXT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ===== 4. APPROVALS (결재) =====
CREATE TABLE approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_request_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approval_step VARCHAR(50) NOT NULL,
    comment TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (budget_request_id) REFERENCES budget_requests(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

--===== 5. NOTIFICATIONS (알림) =====
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    budget_request_id BIGINT NOT NULL,
    message TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (budget_request_id) REFERENCES budget_requests(id)
);